[package]
name = "rust2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cab = "0.6.0"
fs = "0.0.5"
io = "0.0.2"
